# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
#url: "github.tips"
repository: pauliver/github.tips

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# aux_links:
#  ![](https://github.com/pauliver/github.tips/workflows/Jekyll%20site%20CI/badge.svg)

