# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
#url: "github.tips"
repository: pauliver/github.tips

title: GitHub Tips

description: A place for Tips and Tricks _(for GitHub)_

permalink: pretty

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

aux_links:
  ![](https://github.com/pauliver/github.tips/workflows/Jekyll%20site%20CI/badge.svg)

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-159396166-4
